---
version: '3.4'
x-vars:
  PATH:   &PATH    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CG:     &CG      /sys/fs/cgroup:/sys/fs/cgroup:ro
  DNS:    &DNS
    - 8.8.8.8
    - 1.1.1.1
  DF: &DF alpine.Dockerfile
  IMG: &IMG alpine-pueue
  BIMG: &BIMG alpine-binaries
  RESTIC-IMG: &RESTIC-IMG alpine-restic
  RESTIC-BUILD: &RESTIC-BUILD
    dockerfile: alpine-restic
    context: .

  BIM: &BIM
    dockerfile: *IMG
    context: .

  ALPINE: &ALPINE
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    working_dir: /root/.config

  FEDORA: &FEDORA
    tty: yes
    dns: *DNS
    image: *IMG
    build:
      dockerfile: fedora.Dockerfile
      context: ./docker
    environment:
     - *PATH
    working_dir: /root/.config

x-disabledservices:
  SCHED: &SCHED
    tty: false
    hostname: sched0
    image: fedora-pueue
    build:
      dockerfile: fedora-pueue.Dockerfile
      context: ./docker
    volumes:
      - ./docker/files/net-pueue.yml:/root/.config/pueue/pueue.yml
    working_dir: /root/.config/pueue
    command: sh -c "while :; do date; sleep 5; done"

  x-webhook: &WEBHOOK
    tty: false
    image: fedora-webhook
    build:
      dockerfile: fedora-webhook.Dockerfile
      context: ./docker
    ports: 
      - 35001:8000
    volumes:
      - ./docker/files/webhook_server.yml:/root/.config/webhook_server.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    working_dir: /root/.config
    command: /usr/bin/webhookserver
    depends_on:
      - "pueued"    


  x-restic-rest-server: &RESTIC-REST-SERVER
    tty: false
    hostname: restic-rest-server
    image: fedora-restic-rest-server
    build:
      dockerfile: fedora-restic.Dockerfile
      context: ./docker
    dns: *DNS
    ports: 
      - 35005:8000
    working_dir: /root
    command: /usr/bin/rest-server --no-auth --path /data
    volumes:
      - ./data:/data

  x-iodine0: &IO0
    privileged: yes
    tty: false
    image: fedora-iodine
    build: 
      dockerfile: fedora-iodine.Dockerfile
      context: ./docker
    restart: always
    working_dir: /root/
    environment:
     - *PATH
     - IODINE_PASS={{IODINE_PASS}}
     - DTUN_DOMAIN=io0.{{DTUN}}
     - DTUN_DEVICE=dnsc0
    entrypoint: /iodine.sh
    depends_on: []

  x-iodined: &IODINED
    privileged: yes
    tty: false
    image: fedora-iodine
    build: 
      dockerfile: fedora-iodine.Dockerfile
      context: ./docker
    ports: 
      - "53:53/udp"
    restart: always
    working_dir: /root/
    environment:
     - *PATH
     - IODINED_PASS={{IODINE_PASS}}
     - DTUN_DOMAIN={{DTUN}}
     - DTUN_DEVICE=dnsh0
     - DTUN_PORT=53
     - DTUN_CIDR=10.232.229.0/24
    depends_on: []
    entrypoint: /iodined.sh
#      - "webhook"    

  x-gottyd: &GOTTYD
    tty: false
    image: fedora-gottyd
    build: 
      dockerfile: fedora-gottyd.Dockerfile
      context: ./docker
    ports: 
      - "18105:18105/tcp"
    restart: always
    working_dir: /root/
    command: sleep 666 #/usr/bin/gotty /bin/sh
    environment:
     - GOTTY_PERMIT_WRITE=1
     - GOTTY_PORT=19501 
     - GOTTY_RECONNECT=1 
     - GOTTY_RECONNECT_TIME=5 

  x-ttyd: &TTYD
    tty: false
    image: fedora-ttyd
    build: 
      dockerfile: fedora-ttyd.Dockerfile
      context: ./docker
    ports: 
      - "18106:18106/tcp"
    restart: always
    working_dir: /root/
    command: /usr/bin/ttyd -t fontSize=30  -p 18105 -t disableLeaveAlert=true -- sh
    #entrypoint: /usr/bin/ttyd -t fontSize=30  -p 18101 -t disableLeaveAlert=true -- /bin/zsh -il

  x-glue-c0: &GC0
    image: fedora-client
    build: 
      dockerfile: fedora-client.Dockerfile
      context: ./docker
    privileged: no
    tty: yes
    working_dir: /root

  x-glue-c1: &GC1
    image: fedora-client
    build: 
      dockerfile: fedora-client.Dockerfile
      context: ./docker
    privileged: no
    tty: yes
    working_dir: /root
    network_mode: "service:glue"
    depends_on:
      - glue

  x-glue: &GLUE
    image: glue
    privileged: yes
    cap_add:
      - NET_ADMIN
    build: 
      dockerfile: glue.Dockerfile
      context: ./docker
    tty: false
    hostname: glue
    working_dir: /etc/wireguard
    ports: 
      - 35501:35501/tcp
    volumes:
      - ./wireguard:/gluetun
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - LOG_LEVEL=debug
      - VPN_TYPE=wireguard
      - VPNSP=custom
      - WIREGUARD_ENDPOINT_IP={{WIREGUARD_HOST}}
      - WIREGUARD_ENDPOINT_PORT={{WIREGUARD_PORT}}
      - WIREGUARD_PUBLIC_KEY={{WIREGUARD_PUBLIC_KEY}}
      - WIREGUARD_PRIVATE_KEY={{WIREGUARD_PRIVATE_KEY}}
      - WIREGUARD_ADDRESS={{WIREGUARD_ADDRESS}}
      - TZ=
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_STEALTH=off
      - HTTPPROXY_PORT=35501
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - FIREWALL_VPN_INPUT_PORTS=55101,55102
      #-HTTPPROXY_USER 
      #-HTTPPROXY_PASSWORD 


  x-guard: &GUARD
    tty: false
    hostname: guard
    image: fedora-guard
    build:
      dockerfile: fedora-guard.Dockerfile
      context: ./docker
    ports: 
      - "35001:35001"
    volumes:
      - /dev/net/tun:/dev/net/tun
    working_dir: /etc/wireguard
    sysctls:
     - net.ipv4.ip_forward=1
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=debug
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    privileged: yes
#    command: /usr/bin/pueued -c /root/.config/pueue/pueue.yml -vv

        
  x-pueued: &PUEUED
    tty: false
    hostname: pueued
    image: fedora-pueue
    build:
      dockerfile: fedora-pueue.Dockerfile
      context: ./docker
    ports: 
      - "15002:6924"
    volumes:
      - ./docker/files/pueue.yml:/root/.config/pueue/pueue.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    working_dir: /root/.config/pueue
    command: /usr/bin/pueued -c /root/.config/pueue/pueue.yml -vv

  XXXXXXXXXXX:

    sched: *SCHED

    webhook: *WEBHOOK

    gc0: *GC0
    glue: *GLUE
    gc1: *GC1
    io0: *IO0




services:
    pueued: *PUEUED

    guard: *GUARD
    iodined: *IODINED
    restic-rest-server: *RESTIC-REST-SERVER
    ttyd: *TTYD
    gottyd: *GOTTYD






