---
version: '3.4'
x-vars:
  PATH:   &PATH    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CG:     &CG      /sys/fs/cgroup:/sys/fs/cgroup:ro
  DNS:    &DNS
    - 8.8.8.8
    - 1.1.1.1
  DF: &DF alpine.Dockerfile
  IMG: &IMG alpine-pueue-container:latest
  BUILD: &BUILD
    dockerfile: *DF
    context: .
  ALPINE: &ALPINE
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config

  FEDORA: &FEDORA
    tty: yes
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config



services:
  webhook0:
    tty: yes
    hostname: webhook0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - "1212:1212"
    volumes:
      - ./files/webhook_server.yml:/root/.config/webhook_server.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    working_dir: /root/.config/pueue
    command: webhookserver

  pueued0:
    tty: yes
    hostname: pueued0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - "1313:1313"
    volumes:
      - ./files/pueue.yml:/root/.config/pueue/pueue.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    restart: always
    working_dir: /root/.config/pueue
    command: pueued -c /root/.config/pueue/pueue.yml --verbose

  iodined0:
    privileged: yes
    tty: yes
    container_name: iodined0
    hostname: iodined0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - "9553:53"
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config/pueue
    command: "iodined -d dns0 -p 53 -f -c -i 300 10.232.229.0/24 t2.dtun.vpntech.net"






