---
version: '3.4'
x-vars:
  PATH:   &PATH    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CG:     &CG      /sys/fs/cgroup:/sys/fs/cgroup:ro
  DNS:    &DNS
    - 8.8.8.8
    - 1.1.1.1
  DF: &DF ./alpine.Dockerfile
  IMG: &IMG localhost/alpine-pueue:latest
  BIMG: &BIMG alpine-binaries:latest
  BUILD: &BUILD
    dockerfile: *DF
    context: .
  ALPINE: &ALPINE
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config

  FEDORA: &FEDORA
    tty: yes
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config

x-disabledservices:
  scheduler0:
    tty: no
    hostname: scheduler0
    image: *IMG
    build: *BUILD
    dns: *DNS
    volumes:
      - ./files/net-pueue.yml:/root/.config/pueue/pueue.yml
    restart: always
    working_dir: /root/.config/pueue
    command: sh -c "while :; do date; /bin/pueue status; sleep 5; done"


services:

  pueued0:
    tty: no
    hostname: pueued0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - "15002:6924"
    volumes:
      - ./files/pueue.yml:/root/.config/pueue/pueue.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    restart: always
    working_dir: /root/.config/pueue
    command: /bin/pueued -vv -c /root/.config/pueue/pueue.yml

  iodined0:
    privileged: yes
    tty: no
    container_name: iodined0
    hostname: iodined0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - "54:53/udp"
    environment:
     - *PATH
    restart: always
    working_dir: /root/
    command: /bin/iodined -d dns0 -p 53 -f -c -i 300 10.232.229.0/24 t2.dtun.vpntech.net
    volumes:
      - *CG

  webhook0:
    tty: no
    hostname: webhook0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - 35001:8000
    volumes:
      - ./files/webhook_server.yml:/root/.config/webhook_server.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    working_dir: /root/.config
    command: /bin/webhookserver


  restic0:
    tty: no
    hostname: restic0
    image: *IMG
    build: *BUILD
    dns: *DNS
    ports: 
      - 35005:8000
    working_dir: /root
    command: /usr/bin/restic serve






