---
version: '3.4'
x-vars:
  PATH:   &PATH    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CG:     &CG      /sys/fs/cgroup:/sys/fs/cgroup:ro
  DNS:    &DNS
    - 8.8.8.8
    - 1.1.1.1
  DF: &DF alpine.Dockerfile
  IMG: &IMG alpine-pueue
  RMG: &RMG alpine-restic
  BIMG: &BIMG alpine-binaries
  RESTIC-IMG: &RESTIC-IMG alpine-restic
  RESTIC-BUILD: &RESTIC-BUILD
    dockerfile: alpine-restic
    context: .
  BRB: &BRB
    dockerfile: *RMG
    context: .
  BIM: &BIM
    dockerfile: *IMG
    context: .
  ALPINE: &ALPINE
    dns: *DNS
    build: 
      dockerfile: *DF
      context: .
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config

  FEDORA: &FEDORA
    tty: yes
    dns: *DNS
    image: *IMG
    build: *BIM
    environment:
     - *PATH
    restart: always
    working_dir: /root/.config

x-disabledservices:
  SCHED: &SCHED
    tty: false
    hostname: scheduler0
    image: *IMG
    build: *BIM
    dns: *DNS
    volumes:
      - ./files/net-pueue.yml:/root/.config/pueue/pueue.yml
    restart: always
    working_dir: /root/.config/pueue
    command: sh -c "while :; do date; /bin/pueue status; sleep 5; done"

  WEBHOOK: &WEBHOOK
    tty: false
    hostname: webhook0
    image: *IMG
    build: *BIM
    dns: *DNS
    ports: 
      - 35001:8000
    volumes:
      - ./files/webhook_server.yml:/root/.config/webhook_server.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    working_dir: /root/.config
    command: /bin/webhookserver

  PUEUED: &PUEUED
    tty: no
    hostname: pueued0
    image: *IMG
    build: *BIM
    dns: *DNS
    ports: 
      - "15002:6924"
    volumes:
      - ./files/pueue.yml:/root/.config/pueue/pueue.yml
      - /tmp/pueued.sock:/root/.local/share/pueue/pueue.socket
    restart: always
    working_dir: /root/.config/pueue
    command: sleep 666 
 #   command: /bin/pueued -vv -c /root/.config/pueue/pueue.yml


  RESTIC: &RESTIC
    tty: true
    hostname: restic0
    image: *RESTIC-IMG
    build: *RESTIC-BUILD
    dns: *DNS
    ports: 
      - 35005:8000
    working_dir: /root
    command: sleep 666 
#/usr/bin/restic rest-serve
    volumes:
      - ./data:/data

x-iodined: &IODINED
    privileged: yes
    tty: false
    container_name: iodined0
    hostname: iodined0
    image: alpine-pueued
    build: 
      dockerfile: fedora.Dockerfile
      context: ./docker
    dns: *DNS
    ports: 
      - "54:53/udp"
    environment:
     - *PATH
    restart: always
    working_dir: /root/
 #   command: /bin/iodined -d dns0 -p 53 -f -c -i 300 10.232.229.0/24 t2.dtun.vpntech.net
    command: sleep 666 
    volumes:
      - *CG

services:
  iodined0: 
    <<: *IODINED
#  pueued0: *PUEUED
#  r0: *RESTIC









